// This app is Vite + TanStack Start, not Next.js. It previously extended
// eslint-config-next (a leftover from the Next.js migration), which is not a
// declared dependency here and cannot resolve its own react-hooks plugin —
// `npm run lint:web` crashed before linting a single file.
import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  globalIgnores([
    "dist/**",
    "build/**",
    ".output/**",
    ".wrangler/**",
    "playwright-report/**",
    "test-results/**",
    "shots/**",
    // Playwright specs, not React: the `use` fixture parameter trips
    // react-hooks/rules-of-hooks, and assertion expressions trip
    // no-unused-expressions.
    "e2e/**",
    // Regenerated by the TanStack Router plugin on every dev-server start.
    "src/routeTree.gen.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
]);
