/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppVehiclesRouteImport } from './routes/app.vehicles'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyDeliveriesRouteImport } from './routes/app.my-deliveries'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as AppDispatchesRouteImport } from './routes/app.dispatches'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppAiAssistantRouteImport } from './routes/app.ai-assistant'
import { Route as AppVehiclesCreateRouteImport } from './routes/app.vehicles.create'
import { Route as AppVehiclesVehicleIdRouteImport } from './routes/app.vehicles.$vehicleId'
import { Route as AppSettingsPageRouteImport } from './routes/app/settings/page'
import { Route as AppReportsLayoutRouteImport } from './routes/app/reports/layout'
import { Route as AppOrdersLayoutRouteImport } from './routes/app/orders/layout'
import { Route as AppOrdersCreateRouteImport } from './routes/app.orders.create'
import { Route as AppOrdersOrderIdRouteImport } from './routes/app.orders.$orderId'
import { Route as AppNotificationsLayoutRouteImport } from './routes/app/notifications/layout'
import { Route as AppMyDeliveriesLayoutRouteImport } from './routes/app/my-deliveries/layout'
import { Route as AppFinanceLayoutRouteImport } from './routes/app/finance/layout'
import { Route as AppDriversLayoutRouteImport } from './routes/app/drivers/layout'
import { Route as AppDriversCreateRouteImport } from './routes/app.drivers.create'
import { Route as AppDriversDriverIdRouteImport } from './routes/app.drivers.$driverId'
import { Route as AppDispatchesCreateRouteImport } from './routes/app.dispatches.create'
import { Route as AppDispatchesDispatchIdRouteImport } from './routes/app.dispatches.$dispatchId'
import { Route as AppDispatchLayoutRouteImport } from './routes/app/dispatch/layout'
import { Route as AppCustomersLayoutRouteImport } from './routes/app/customers/layout'
import { Route as AppCustomersCreateRouteImport } from './routes/app.customers.create'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AppAiAssistantLayoutRouteImport } from './routes/app/ai-assistant/layout'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDeliveriesRoute = AppMyDeliveriesRouteImport.update({
  id: '/my-deliveries',
  path: '/my-deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchesRoute = AppDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesCreateRoute = AppVehiclesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesVehicleIdRoute = AppVehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppSettingsPageRoute = AppSettingsPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsLayoutRoute = AppReportsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppOrdersLayoutRoute = AppOrdersLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersCreateRoute = AppOrdersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppNotificationsLayoutRoute = AppNotificationsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppMyDeliveriesLayoutRoute = AppMyDeliveriesLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppMyDeliveriesRoute,
} as any)
const AppFinanceLayoutRoute = AppFinanceLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppDriversLayoutRoute = AppDriversLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppDriversCreateRoute = AppDriversCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppDriversDriverIdRoute = AppDriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => AppDriversRoute,
} as any)
const AppDispatchesCreateRoute = AppDispatchesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppDispatchesRoute,
} as any)
const AppDispatchesDispatchIdRoute = AppDispatchesDispatchIdRouteImport.update({
  id: '/$dispatchId',
  path: '/$dispatchId',
  getParentRoute: () => AppDispatchesRoute,
} as any)
const AppDispatchLayoutRoute = AppDispatchLayoutRouteImport.update({
  id: '/dispatch/layout',
  path: '/dispatch/layout',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersLayoutRoute = AppCustomersLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCustomersCreateRoute = AppCustomersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppAiAssistantLayoutRoute = AppAiAssistantLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AppAiAssistantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-assistant': typeof AppAiAssistantRouteWithChildren
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dispatches': typeof AppDispatchesRouteWithChildren
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/my-deliveries': typeof AppMyDeliveriesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/vehicles': typeof AppVehiclesRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/ai-assistant/layout': typeof AppAiAssistantLayoutRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/customers/layout': typeof AppCustomersLayoutRoute
  '/app/dispatch/layout': typeof AppDispatchLayoutRoute
  '/app/dispatches/$dispatchId': typeof AppDispatchesDispatchIdRoute
  '/app/dispatches/create': typeof AppDispatchesCreateRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/drivers/create': typeof AppDriversCreateRoute
  '/app/drivers/layout': typeof AppDriversLayoutRoute
  '/app/finance/layout': typeof AppFinanceLayoutRoute
  '/app/my-deliveries/layout': typeof AppMyDeliveriesLayoutRoute
  '/app/notifications/layout': typeof AppNotificationsLayoutRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/orders/create': typeof AppOrdersCreateRoute
  '/app/orders/layout': typeof AppOrdersLayoutRoute
  '/app/reports/layout': typeof AppReportsLayoutRoute
  '/app/settings/page': typeof AppSettingsPageRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai-assistant': typeof AppAiAssistantRouteWithChildren
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dispatches': typeof AppDispatchesRouteWithChildren
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/my-deliveries': typeof AppMyDeliveriesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/vehicles': typeof AppVehiclesRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app': typeof AppIndexRoute
  '/app/ai-assistant/layout': typeof AppAiAssistantLayoutRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/customers/layout': typeof AppCustomersLayoutRoute
  '/app/dispatch/layout': typeof AppDispatchLayoutRoute
  '/app/dispatches/$dispatchId': typeof AppDispatchesDispatchIdRoute
  '/app/dispatches/create': typeof AppDispatchesCreateRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/drivers/create': typeof AppDriversCreateRoute
  '/app/drivers/layout': typeof AppDriversLayoutRoute
  '/app/finance/layout': typeof AppFinanceLayoutRoute
  '/app/my-deliveries/layout': typeof AppMyDeliveriesLayoutRoute
  '/app/notifications/layout': typeof AppNotificationsLayoutRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/orders/create': typeof AppOrdersCreateRoute
  '/app/orders/layout': typeof AppOrdersLayoutRoute
  '/app/reports/layout': typeof AppReportsLayoutRoute
  '/app/settings/page': typeof AppSettingsPageRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-assistant': typeof AppAiAssistantRouteWithChildren
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/dispatches': typeof AppDispatchesRouteWithChildren
  '/app/drivers': typeof AppDriversRouteWithChildren
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/my-deliveries': typeof AppMyDeliveriesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/vehicles': typeof AppVehiclesRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/ai-assistant/layout': typeof AppAiAssistantLayoutRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/customers/layout': typeof AppCustomersLayoutRoute
  '/app/dispatch/layout': typeof AppDispatchLayoutRoute
  '/app/dispatches/$dispatchId': typeof AppDispatchesDispatchIdRoute
  '/app/dispatches/create': typeof AppDispatchesCreateRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/drivers/create': typeof AppDriversCreateRoute
  '/app/drivers/layout': typeof AppDriversLayoutRoute
  '/app/finance/layout': typeof AppFinanceLayoutRoute
  '/app/my-deliveries/layout': typeof AppMyDeliveriesLayoutRoute
  '/app/notifications/layout': typeof AppNotificationsLayoutRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/orders/create': typeof AppOrdersCreateRoute
  '/app/orders/layout': typeof AppOrdersLayoutRoute
  '/app/reports/layout': typeof AppReportsLayoutRoute
  '/app/settings/page': typeof AppSettingsPageRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai-assistant'
    | '/app/customers'
    | '/app/dispatches'
    | '/app/drivers'
    | '/app/finance'
    | '/app/my-deliveries'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/vehicles'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/app/'
    | '/app/ai-assistant/layout'
    | '/app/customers/$customerId'
    | '/app/customers/create'
    | '/app/customers/layout'
    | '/app/dispatch/layout'
    | '/app/dispatches/$dispatchId'
    | '/app/dispatches/create'
    | '/app/drivers/$driverId'
    | '/app/drivers/create'
    | '/app/drivers/layout'
    | '/app/finance/layout'
    | '/app/my-deliveries/layout'
    | '/app/notifications/layout'
    | '/app/orders/$orderId'
    | '/app/orders/create'
    | '/app/orders/layout'
    | '/app/reports/layout'
    | '/app/settings/page'
    | '/app/vehicles/$vehicleId'
    | '/app/vehicles/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai-assistant'
    | '/app/customers'
    | '/app/dispatches'
    | '/app/drivers'
    | '/app/finance'
    | '/app/my-deliveries'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/vehicles'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/app'
    | '/app/ai-assistant/layout'
    | '/app/customers/$customerId'
    | '/app/customers/create'
    | '/app/customers/layout'
    | '/app/dispatch/layout'
    | '/app/dispatches/$dispatchId'
    | '/app/dispatches/create'
    | '/app/drivers/$driverId'
    | '/app/drivers/create'
    | '/app/drivers/layout'
    | '/app/finance/layout'
    | '/app/my-deliveries/layout'
    | '/app/notifications/layout'
    | '/app/orders/$orderId'
    | '/app/orders/create'
    | '/app/orders/layout'
    | '/app/reports/layout'
    | '/app/settings/page'
    | '/app/vehicles/$vehicleId'
    | '/app/vehicles/create'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai-assistant'
    | '/app/customers'
    | '/app/dispatches'
    | '/app/drivers'
    | '/app/finance'
    | '/app/my-deliveries'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/vehicles'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/app/'
    | '/app/ai-assistant/layout'
    | '/app/customers/$customerId'
    | '/app/customers/create'
    | '/app/customers/layout'
    | '/app/dispatch/layout'
    | '/app/dispatches/$dispatchId'
    | '/app/dispatches/create'
    | '/app/drivers/$driverId'
    | '/app/drivers/create'
    | '/app/drivers/layout'
    | '/app/finance/layout'
    | '/app/my-deliveries/layout'
    | '/app/notifications/layout'
    | '/app/orders/$orderId'
    | '/app/orders/create'
    | '/app/orders/layout'
    | '/app/reports/layout'
    | '/app/settings/page'
    | '/app/vehicles/$vehicleId'
    | '/app/vehicles/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-deliveries': {
      id: '/app/my-deliveries'
      path: '/my-deliveries'
      fullPath: '/app/my-deliveries'
      preLoaderRoute: typeof AppMyDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatches': {
      id: '/app/dispatches'
      path: '/dispatches'
      fullPath: '/app/dispatches'
      preLoaderRoute: typeof AppDispatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-assistant': {
      id: '/app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/app/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehicles/create': {
      id: '/app/vehicles/create'
      path: '/create'
      fullPath: '/app/vehicles/create'
      preLoaderRoute: typeof AppVehiclesCreateRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/app/vehicles/$vehicleId': {
      id: '/app/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/app/vehicles/$vehicleId'
      preLoaderRoute: typeof AppVehiclesVehicleIdRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/app/settings/page': {
      id: '/app/settings/page'
      path: '/page'
      fullPath: '/app/settings/page'
      preLoaderRoute: typeof AppSettingsPageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/reports/layout': {
      id: '/app/reports/layout'
      path: '/layout'
      fullPath: '/app/reports/layout'
      preLoaderRoute: typeof AppReportsLayoutRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/orders/layout': {
      id: '/app/orders/layout'
      path: '/layout'
      fullPath: '/app/orders/layout'
      preLoaderRoute: typeof AppOrdersLayoutRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/orders/create': {
      id: '/app/orders/create'
      path: '/create'
      fullPath: '/app/orders/create'
      preLoaderRoute: typeof AppOrdersCreateRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/orders/$orderId': {
      id: '/app/orders/$orderId'
      path: '/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/notifications/layout': {
      id: '/app/notifications/layout'
      path: '/layout'
      fullPath: '/app/notifications/layout'
      preLoaderRoute: typeof AppNotificationsLayoutRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/app/my-deliveries/layout': {
      id: '/app/my-deliveries/layout'
      path: '/layout'
      fullPath: '/app/my-deliveries/layout'
      preLoaderRoute: typeof AppMyDeliveriesLayoutRouteImport
      parentRoute: typeof AppMyDeliveriesRoute
    }
    '/app/finance/layout': {
      id: '/app/finance/layout'
      path: '/layout'
      fullPath: '/app/finance/layout'
      preLoaderRoute: typeof AppFinanceLayoutRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/drivers/layout': {
      id: '/app/drivers/layout'
      path: '/layout'
      fullPath: '/app/drivers/layout'
      preLoaderRoute: typeof AppDriversLayoutRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/app/drivers/create': {
      id: '/app/drivers/create'
      path: '/create'
      fullPath: '/app/drivers/create'
      preLoaderRoute: typeof AppDriversCreateRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/app/drivers/$driverId': {
      id: '/app/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/app/drivers/$driverId'
      preLoaderRoute: typeof AppDriversDriverIdRouteImport
      parentRoute: typeof AppDriversRoute
    }
    '/app/dispatches/create': {
      id: '/app/dispatches/create'
      path: '/create'
      fullPath: '/app/dispatches/create'
      preLoaderRoute: typeof AppDispatchesCreateRouteImport
      parentRoute: typeof AppDispatchesRoute
    }
    '/app/dispatches/$dispatchId': {
      id: '/app/dispatches/$dispatchId'
      path: '/$dispatchId'
      fullPath: '/app/dispatches/$dispatchId'
      preLoaderRoute: typeof AppDispatchesDispatchIdRouteImport
      parentRoute: typeof AppDispatchesRoute
    }
    '/app/dispatch/layout': {
      id: '/app/dispatch/layout'
      path: '/dispatch/layout'
      fullPath: '/app/dispatch/layout'
      preLoaderRoute: typeof AppDispatchLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/layout': {
      id: '/app/customers/layout'
      path: '/layout'
      fullPath: '/app/customers/layout'
      preLoaderRoute: typeof AppCustomersLayoutRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/app/customers/create': {
      id: '/app/customers/create'
      path: '/create'
      fullPath: '/app/customers/create'
      preLoaderRoute: typeof AppCustomersCreateRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/app/ai-assistant/layout': {
      id: '/app/ai-assistant/layout'
      path: '/layout'
      fullPath: '/app/ai-assistant/layout'
      preLoaderRoute: typeof AppAiAssistantLayoutRouteImport
      parentRoute: typeof AppAiAssistantRoute
    }
  }
}

interface AppAiAssistantRouteChildren {
  AppAiAssistantLayoutRoute: typeof AppAiAssistantLayoutRoute
}

const AppAiAssistantRouteChildren: AppAiAssistantRouteChildren = {
  AppAiAssistantLayoutRoute: AppAiAssistantLayoutRoute,
}

const AppAiAssistantRouteWithChildren = AppAiAssistantRoute._addFileChildren(
  AppAiAssistantRouteChildren,
)

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersCreateRoute: typeof AppCustomersCreateRoute
  AppCustomersLayoutRoute: typeof AppCustomersLayoutRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersCreateRoute: AppCustomersCreateRoute,
  AppCustomersLayoutRoute: AppCustomersLayoutRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppDispatchesRouteChildren {
  AppDispatchesDispatchIdRoute: typeof AppDispatchesDispatchIdRoute
  AppDispatchesCreateRoute: typeof AppDispatchesCreateRoute
}

const AppDispatchesRouteChildren: AppDispatchesRouteChildren = {
  AppDispatchesDispatchIdRoute: AppDispatchesDispatchIdRoute,
  AppDispatchesCreateRoute: AppDispatchesCreateRoute,
}

const AppDispatchesRouteWithChildren = AppDispatchesRoute._addFileChildren(
  AppDispatchesRouteChildren,
)

interface AppDriversRouteChildren {
  AppDriversDriverIdRoute: typeof AppDriversDriverIdRoute
  AppDriversCreateRoute: typeof AppDriversCreateRoute
  AppDriversLayoutRoute: typeof AppDriversLayoutRoute
}

const AppDriversRouteChildren: AppDriversRouteChildren = {
  AppDriversDriverIdRoute: AppDriversDriverIdRoute,
  AppDriversCreateRoute: AppDriversCreateRoute,
  AppDriversLayoutRoute: AppDriversLayoutRoute,
}

const AppDriversRouteWithChildren = AppDriversRoute._addFileChildren(
  AppDriversRouteChildren,
)

interface AppFinanceRouteChildren {
  AppFinanceLayoutRoute: typeof AppFinanceLayoutRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceLayoutRoute: AppFinanceLayoutRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppMyDeliveriesRouteChildren {
  AppMyDeliveriesLayoutRoute: typeof AppMyDeliveriesLayoutRoute
}

const AppMyDeliveriesRouteChildren: AppMyDeliveriesRouteChildren = {
  AppMyDeliveriesLayoutRoute: AppMyDeliveriesLayoutRoute,
}

const AppMyDeliveriesRouteWithChildren = AppMyDeliveriesRoute._addFileChildren(
  AppMyDeliveriesRouteChildren,
)

interface AppNotificationsRouteChildren {
  AppNotificationsLayoutRoute: typeof AppNotificationsLayoutRoute
}

const AppNotificationsRouteChildren: AppNotificationsRouteChildren = {
  AppNotificationsLayoutRoute: AppNotificationsLayoutRoute,
}

const AppNotificationsRouteWithChildren =
  AppNotificationsRoute._addFileChildren(AppNotificationsRouteChildren)

interface AppOrdersRouteChildren {
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppOrdersCreateRoute: typeof AppOrdersCreateRoute
  AppOrdersLayoutRoute: typeof AppOrdersLayoutRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppOrdersCreateRoute: AppOrdersCreateRoute,
  AppOrdersLayoutRoute: AppOrdersLayoutRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsLayoutRoute: typeof AppReportsLayoutRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsLayoutRoute: AppReportsLayoutRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsPageRoute: typeof AppSettingsPageRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsPageRoute: AppSettingsPageRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppVehiclesRouteChildren {
  AppVehiclesVehicleIdRoute: typeof AppVehiclesVehicleIdRoute
  AppVehiclesCreateRoute: typeof AppVehiclesCreateRoute
}

const AppVehiclesRouteChildren: AppVehiclesRouteChildren = {
  AppVehiclesVehicleIdRoute: AppVehiclesVehicleIdRoute,
  AppVehiclesCreateRoute: AppVehiclesCreateRoute,
}

const AppVehiclesRouteWithChildren = AppVehiclesRoute._addFileChildren(
  AppVehiclesRouteChildren,
)

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDispatchesRoute: typeof AppDispatchesRouteWithChildren
  AppDriversRoute: typeof AppDriversRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppMyDeliveriesRoute: typeof AppMyDeliveriesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRouteWithChildren
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppVehiclesRoute: typeof AppVehiclesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDispatchLayoutRoute: typeof AppDispatchLayoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRouteWithChildren,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDispatchesRoute: AppDispatchesRouteWithChildren,
  AppDriversRoute: AppDriversRouteWithChildren,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppMyDeliveriesRoute: AppMyDeliveriesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRouteWithChildren,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppVehiclesRoute: AppVehiclesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDispatchLayoutRoute: AppDispatchLayoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
