/** Mirrors backend DriverActionEventType strings. */
export type DriverActionEventType =
  | 'DRIVER_ACCEPTED'
  | 'DRIVER_REJECTED'
  | 'TRIP_STARTED'
  | 'ARRIVED_PICKUP'
  | 'LOADING'
  | 'IN_TRANSIT'
  | 'DELIVERED'
  | 'BREAK_STARTED'
  | 'BREAK_ENDED'
  | 'POD_UPLOADED'
  | 'FUEL_ADDED'
  | 'EXPENSE_SUBMITTED'
  | 'INSPECTION_COMPLETED'
  | 'OPERATIONAL_STATUS_CHANGED'
  | 'STATUS_CHANGED';

export const DRIVER_ACTION_EVENT_TYPES: readonly DriverActionEventType[] = [
  'DRIVER_ACCEPTED',
  'DRIVER_REJECTED',
  'TRIP_STARTED',
  'ARRIVED_PICKUP',
  'LOADING',
  'IN_TRANSIT',
  'DELIVERED',
  'BREAK_STARTED',
  'BREAK_ENDED',
  'POD_UPLOADED',
  'FUEL_ADDED',
  'EXPENSE_SUBMITTED',
  'INSPECTION_COMPLETED',
  'OPERATIONAL_STATUS_CHANGED',
  'STATUS_CHANGED',
] as const;
